#ifndef SHADI_HPP
#define SHADI_HPP
namespace stmsl {


const type<temp::inst> _image2D("image2D",type::ty::Image2D);
const type<temp::inst> _image2D("image3D",type::ty::Image3D);
const type<temp::inst> _image2D("Sampler",type::ty::Sampler);
const type<temp::inst> _Void("void",type::prim::Void);const type<temp::meta> m_Void("void",type::prim::Void);
const type<temp::inst> _Float("Float",type::prim::Float);
const type<temp::inst> _Double("Float",type::prim::Double);
const type<temp::inst> _UInt("UInt",type::prim::Uint);
const type<temp::inst> _Int("Int",type::prim::Int);
const type<temp::inst> _Bool("Bool",type::prim::Bool);

const type<temp::meta> Vec("Vec",1);
const type<temp::meta> Mat("Mat",2);

using UsingInst = typename stmt<temp::inst>::Using;

const type<temp::inst> vec2("vec2",Vec,&_Float,2);
const type<temp::inst> vec3("vec3",Vec,&_Float,3);
const type<temp::inst> vec4("vec4",Vec,&_Float,4);
const type<temp::inst> vec2("vec2",Vec,&_Double,2);
const type<temp::inst> vec3("vec3",Vec,&_Double,3);
const type<temp::inst> vec4("vec4",Vec,&_Double,4);
const type<temp::inst> ivec2("ivec2",Vec,&_Int,2);
const type<temp::inst> ivec3("ivec3",Vec,&_Int,3);
const type<temp::inst> ivec4("ivec4",Vec,&_Int,4);
const type<temp::inst> uvec2("uvec2",Vec,&_UInt,2);
const type<temp::inst> uvec3("uvec3",Vec,&_UInt,3);
const type<temp::inst> uvec4("uvec4",Vec,&_UInt,4);
const type<temp::inst> ivec2("ivec2",Vec,&_Int,2);
const type<temp::inst> ivec3("ivec3",Vec,&_Int,3);
const type<temp::inst> ivec4("ivec4",Vec,&_Int,4);
const type<temp::inst> bvec2("bvec2",Vec,&_Bool,2);
const type<temp::inst> bvec3("bvec3",Vec,&_Bool,3);
const type<temp::inst> bvec4("bvec4",Vec,&_Bool,4);
const type<temp::inst> mat2("mat2",Mat,&_Float,2);
const type<temp::inst> mat3("mat3",Mat,&_Float,3);
const type<temp::inst> mat4("mat4",Mat,&_Float,4);
const type<temp::inst> dmat2("mat2",Mat,&_Double,2);
const type<temp::inst> dmat3("mat3",Mat,&_Double,3);
const type<temp::inst> dmat4("mat4",Mat,&_Double,4);
const type<temp::inst> imat2("imat2",Mat,&_Int,2);
const type<temp::inst> imat3("imat3",Mat,&_Int,3);
const type<temp::inst> imat4("imat4",Mat,&_Int,4);
const type<temp::inst> umat2("umat2",Mat,&_UInt,2);
const type<temp::inst> umat3("umat3",Mat,&_UInt,3);
const type<temp::inst> umat4("umat4",Mat,&_UInt,4);
const type<temp::inst> imat2("imat2",Mat,&_Int,2);
const type<temp::inst> imat3("imat3",Mat,&_Int,3);
const type<temp::inst> imat4("imat4",Mat,&_Int,4);
const type<temp::inst> bmat2("bmat2",Mat,&_Bool,2);
const type<temp::inst> bmat3("bmat3",Mat,&_Bool,3);
const type<temp::inst> bmat4("bmat4",Mat,&_Bool,4);
const type<temp::inst> mat2x2("mat2x2",Mat,&_Float,2,2);
const type<temp::inst> mat3x2("mat3x2",Mat,&_Float,3,2);
const type<temp::inst> mat4x2("mat4x2",Mat,&_Float,4,2);
const type<temp::inst> dmat2x2("dmat2x2",Mat,&_Double,2,2);
const type<temp::inst> dmat3x2("dmat3x2",Mat,&_Double,3,2);
const type<temp::inst> dmat4x2("dmat4x2",Mat,&_Double,4,2);
const type<temp::inst> imat2x2("imat2x2",Mat,&_Int,2,2);
const type<temp::inst> imat3x2("imat3x2",Mat,&_Int,3,2);
const type<temp::inst> imat4x2("imat4x2",Mat,&_Int,4,2);
const type<temp::inst> umat2x2("umat2x2",Mat,&_UInt,2,2);
const type<temp::inst> umat3x2("umat3x2",Mat,&_UInt,3,2);
const type<temp::inst> umat4x2("umat4x2",Mat,&_UInt,4,2);
const type<temp::inst> imat2x2("imat2x2",Mat,&_Int,2,2);
const type<temp::inst> imat3x2("imat3x2",Mat,&_Int,3,2);
const type<temp::inst> imat4x2("imat4x2",Mat,&_Int,4,2);
const type<temp::inst> bmat2x2("bmat2x2",Mat,&_Bool,2,2);
const type<temp::inst> bmat3x2("bmat3x2",Mat,&_Bool,3,2);
const type<temp::inst> bmat4x2("bmat4x2",Mat,&_Bool,4,2);//
const type<temp::inst> mat2x3("mat2x3",Mat,&_Float,2,3);
const type<temp::inst> mat3x3("mat3x3",Mat,&_Float,3,3);
const type<temp::inst> mat4x3("mat4x3",Mat,&_Float,4,3);
const type<temp::inst> dmat2x3("dmat2x3",Mat,&_Double,2,3);
const type<temp::inst> dmat3x3("dmat3x3",Mat,&_Double,3,3);
const type<temp::inst> dmat4x3("dmat4x3",Mat,&_Double,4,3);
const type<temp::inst> imat2x3("imat2x3",Mat,&_Int,2,3);
const type<temp::inst> imat3x3("imat3x3",Mat,&_Int,3,3);
const type<temp::inst> imat4x3("imat4x3",Mat,&_Int,4,3);
const type<temp::inst> umat2x3("umat2x3",Mat,&_UInt,2,3);
const type<temp::inst> umat3x3("umat3x3",Mat,&_UInt,3,3);
const type<temp::inst> umat4x3("umat4x3",Mat,&_UInt,4,3);
const type<temp::inst> imat2x3("imat2x3",Mat,&_Int,2,3);
const type<temp::inst> imat3x3("imat3x3",Mat,&_Int,3,3);
const type<temp::inst> imat4x3("imat4x3",Mat,&_Int,4,3);
const type<temp::inst> bmat2x3("bmat2x3",Mat,&_Bool,2,3);
const type<temp::inst> bmat3x3("bmat3x3",Mat,&_Bool,3,3);
const type<temp::inst> bmat4x3("bmat4x3",Mat,&_Bool,4,3);//
const type<temp::inst> mat2x4("mat2x4",Mat,&_Float,2,4);
const type<temp::inst> mat3x4("mat3x4",Mat,&_Float,3,4);
const type<temp::inst> mat4x4("mat4x4",Mat,&_Float,4,4);
const type<temp::inst> dmat2x4("dmat2x4",Mat,&_Double,2,4);
const type<temp::inst> dmat3x4("dmat3x4",Mat,&_Double,3,4);
const type<temp::inst> dmat4x4("dmat4x4",Mat,&_Double,4,4);
const type<temp::inst> imat2x4("imat2x4",Mat,&_Int,2,4);
const type<temp::inst> imat3x4("imat3x4",Mat,&_Int,3,4);
const type<temp::inst> imat4x4("imat4x4",Mat,&_Int,4,4);
const type<temp::inst> umat2x4("umat2x4",Mat,&_UInt,2,4);
const type<temp::inst> umat3x4("umat3x4",Mat,&_UInt,3,4);
const type<temp::inst> umat4x4("umat4x4",Mat,&_UInt,4,4);
const type<temp::inst> imat2x4("imat2x4",Mat,&_Int,2,4);
const type<temp::inst> imat3x4("imat3x4",Mat,&_Int,3,4);
const type<temp::inst> imat4x4("imat4x4",Mat,&_Int,4,4);
const type<temp::inst> bmat2x4("bmat2x4",Mat,&_Bool,2,4);
const type<temp::inst> bmat3x4("bmat3x4",Mat,&_Bool,3,4);
const type<temp::inst> bmat4x4("bmat4x4",Mat,&_Bool,4,4);

#define INTRINSIC_TYS vec2,vec3,vec4,ivec2,ivec3,ivec4,uvec2,uvec3,uvec4,ivec2,ivec3,ivec4,bvec2,bvec3,bvec4,mat2,mat3,mat4,imat2,imat3,imat4,umat2,umat3,umat4,imat2,imat3,imat4,bmat2,bmat3,bmat4,mat2x2,mat3x2,mat4x2,imat2x2,imat3x2,imat4x2,umat2x2,umat3x2,umat4x2,imat2x2,imat3x2,imat4x2,bmat2x2,bmat3x2,bmat4x2,mat2x3,mat3x3,mat4x3,imat2x3,imat3x3,imat4x3,umat2x3,umat3x3,umat4x3,imat2x3,imat3x3,imat4x3,bmat2x3,bmat3x3,bmat4x3,mat2x4,mat3x4,mat4x4,imat2x4,imat3x4,imat4x4,umat2x4,umat3x4,umat4x4,imat2x4,imat3x4,imat4x4,bmat2x4,bmat3x4,bmat4x4
 // ShaderIntrincs
// Trig
const stmt::FuncDecl _acos("acos",{&_Float},{&Float},{});
const stmt::FuncDecl _acosh("acosh");
const stmt::FuncDecl _asin("asin");
const stmt::FuncDecl _asinh("asinh");
const stmt::FuncDecl _atan("atan");
const stmt::FuncDecl _atanh("atanh");
const stmt::FuncDecl _cos("cos");
const stmt::FuncDecl _cosh("cosh");
const stmt::FuncDecl _degrees("degrees");
const stmt::FuncDecl _radians("radians");
const stmt::FuncDecl _sin("sin");
const stmt::FuncDecl _sinh("sinh");
const stmt::FuncDecl _tan("tan");
const stmt::FuncDecl _tanh("tanh");
// Math
const stmt::FuncDecl _abs("abs");
const stmt::FuncDecl _ceil("ceil");
const stmt::FuncDecl _clamp("clamp");
const stmt::FuncDecl _dFdx("dFdx");
const stmt::FuncDecl _dFdy("dFdy");
const stmt::FuncDecl _exp("exp");
const stmt::FuncDecl _exp2("exp2");
const stmt::FuncDecl _floor("floor");
const stmt::FuncDecl _floor("floor");
const stmt::FuncDecl _fma("fma");
const stmt::FuncDecl _fract("fract");
const stmt::FuncDecl _fwidth("fwidth");
const stmt::FuncDecl _inversesqrt("inversesqrt");
const stmt::FuncDecl _isinf("isinf");
const stmt::FuncDecl _isnan("isnan");
const stmt::FuncDecl _log("log");
const stmt::FuncDecl _log2("log2");
const stmt::FuncDecl _max("max");
const stmt::FuncDecl _min("min");
const stmt::FuncDecl _mix("mix");
const stmt::FuncDecl _mod("mod");
const stmt::FuncDecl _modf("modf");
const stmt::FuncDecl _noise("noise");
const stmt::FuncDecl _pow("pow");
const stmt::FuncDecl _round("round");
const stmt::FuncDecl _roundEven("roundEven");
const stmt::FuncDecl _sign("sign");
const stmt::FuncDecl _smoothstep("smoothstep");
const stmt::FuncDecl _sqrt("sqrt");
const stmt::FuncDecl _step("step");
const stmt::FuncDecl _trunc("trunc");
// Flt
const stmt::FuncDecl _floatBitsToInt("floatBitsToInt");
const stmt::FuncDecl _frexp("frexp");
const stmt::FuncDecl _intBitsToFloat("intBitsToFloat");
const stmt::FuncDecl _ldexp("ldexp");
const stmt::FuncDecl _packDouble2x32("packDouble2x32");
const stmt::FuncDecl _packHalf2x16("packHalf2x16");
const stmt::FuncDecl _packUnorm("packUnorm");
const stmt::FuncDecl _unpackDouble2x32("unpackDouble2x32");
const stmt::FuncDecl _unpackHalf2x16("unpackHalf2x16");
const stmt::FuncDecl _unpackUnorm("unpackUnorm");
// Builtin Var

// Make This anonymous
const stmt::VarDecl _gl_PerVertex("gl_PerVertex" ,{qual::qOut},type<temp::inst>(stmt::VarDecl(vec4,"gl_Position"),stmt::VarDecl(_Float,"gl_PointSize"),stmt::VarDecl(_Float,"gl_ClipDistance",type<temp::meta>::ty::arr)));

const stmt::VarDecl _gl_ClipDistance("gl_ClipDistance",  );
const stmt::VarDecl _gl_CullDistance("gl_CullDistance",);
const stmt::VarDecl _gl_FragCoord("gl_FragCoord");
const stmt::VarDecl _gl_FragDepth("gl_FragDepth");
const stmt::VarDecl _gl_FrontFacing("gl_FrontFacing");
const stmt::VarDecl _gl_GlobalInvocationID("gl_GlobalInvocationID");
const stmt::VarDecl _gl_HelperInvocation("gl_HelperInvocation");
const stmt::VarDecl _gl_InstanceID("gl_InstanceID");
const stmt::VarDecl _gl_InvocationID("gl_InvocationID");
const stmt::VarDecl _gl_Layer("gl_Layer");
const stmt::VarDecl _gl_LocalInvocationID("gl_LocalInvocationID");
const stmt::VarDecl _gl_LocalInvocationIndex("gl_LocalInvocationIndex");
const stmt::VarDecl _gl_NumSamples("gl_NumSamples");
const stmt::VarDecl _gl_NumWorkGroups("gl_NumWorkGroups");
const stmt::VarDecl _gl_PatchVerticesIn("gl_PatchVerticesIn");
const stmt::VarDecl _gl_PointCoord("gl_PointCoord");
const stmt::VarDecl _gl_PointSize("gl_PointSize");
const stmt::VarDecl _gl_Position("gl_Position");
const stmt::VarDecl _gl_PrimitiveID("gl_PrimitiveID");
const stmt::VarDecl _gl_PrimitiveIDIn("gl_PrimitiveIDIn");
const stmt::VarDecl _gl_SampleID("gl_SampleID");
const stmt::VarDecl _gl_SampleMask("gl_SampleMask");
const stmt::VarDecl _gl_SampleMaskIn("gl_SampleMaskIn");
const stmt::VarDecl _gl_SamplePosition("gl_SamplePosition");
const stmt::VarDecl _gl_TessCoord("gl_TessCoord");
const stmt::VarDecl _gl_TessLevelInner("gl_TessLevelInner");
const stmt::VarDecl _gl_TessLevelOuter("gl_TessLevelOuter");
const stmt::VarDecl _gl_VertexID("gl_VertexID");
const stmt::VarDecl _gl_ViewportIndex("gl_ViewportIndex");
const stmt::VarDecl _gl_WorkGroupID("gl_WorkGroupID");
const stmt::VarDecl _gl_WorkGroupSize("gl_WorkGroupSize");
// Vector
const stmt::FuncDecl _cross("cross");
const stmt::FuncDecl _distance("distance");
const stmt::FuncDecl _dot("dot");
const stmt::FuncDecl _equal("equal");
const stmt::FuncDecl _faceforward("faceforward");
const stmt::FuncDecl _length("length");
const stmt::FuncDecl _normalize("normalize");
const stmt::FuncDecl _notEqual("notEqual");
const stmt::FuncDecl _reflect("reflect");
const stmt::FuncDecl _refract("refract");
// Component Comparison
const stmt::FuncDecl _all("all");
const stmt::FuncDecl _any("any");
const stmt::FuncDecl _greaterThan("greaterThan");
const stmt::FuncDecl _greaterThanEqual("greaterThanEqual");
const stmt::FuncDecl _lessThan("lessThan");
const stmt::FuncDecl _lessThanEqual("lessThanEqual");
const stmt::FuncDecl _not("not");

// Geometry Shader
const stmt::FuncDecl _EmitStreamVertex("EmitStreamVertex");
const stmt::FuncDecl _EmitVertex("EmitVertex");
const stmt::FuncDecl _EndPrimitive("EndPrimitive");
const stmt::FuncDecl _EndStreamPrimitive("EndStreamPrimitive");
// Texture Sampling
const stmt::FuncDecl _interpolateAtCentroid("interpolateAtCentroid");
const stmt::FuncDecl _interpolateAtOffset("interpolateAtOffset");
const stmt::FuncDecl _interpolateAtSample("interpolateAtSample");
const stmt::FuncDecl _texelFetch("texelFetch");
const stmt::FuncDecl _texelFetchOffset("texelFetchOffset");
const stmt::FuncDecl _texture("texture");
const stmt::FuncDecl _textureGather("textureGather");
const stmt::FuncDecl _textureGatherOffset("textureGatherOffset");
const stmt::FuncDecl _textureGatherOffsets("textureGatherOffsets");
const stmt::FuncDecl _textureGrad("textureGrad");
const stmt::FuncDecl _textureGradOffset("textureGradOffset");
const stmt::FuncDecl _textureLod("textureLod");
const stmt::FuncDecl _textureLodOffset("textureLodOffset");
const stmt::FuncDecl _textureOffset("textureOffset");
const stmt::FuncDecl _textureProj("textureProj");
const stmt::FuncDecl _textureProjGrad("textureProjGrad");
const stmt::FuncDecl _textureProjGradOffset("textureProjGradOffset");
const stmt::FuncDecl _textureProjLod("textureProjLod");
const stmt::FuncDecl _textureProjLodOffset("textureProjLodOffset");
const stmt::FuncDecl _textureProjOffset("textureProjOffset");
const stmt::FuncDecl _textureQueryLevels("textureQueryLevels");
const stmt::FuncDecl _textureQueryLod("textureQueryLod");
const stmt::FuncDecl _textureSamples("textureSamples");
const stmt::FuncDecl _textureSize("textureSize");
// Matrix
const stmt::FuncDecl _determinant("determinant");
const stmt::FuncDecl _groupMemoryBarrier("groupMemoryBarrier");
const stmt::FuncDecl _inverse("inverse");
const stmt::FuncDecl _matrixCompMult("matrixCompMult");
const stmt::FuncDecl _outerProduct("outerProduct");
const stmt::FuncDecl _transpose("transpose");
// Integer
const stmt::FuncDecl _bitCount("bitCount");
const stmt::FuncDecl _bitfieldExtract("bitfieldExtract");
const stmt::FuncDecl _bitfieldInsert("bitfieldInsert");
const stmt::FuncDecl _bitfieldReverse("bitfieldReverse");
const stmt::FuncDecl _findLSB("findLSB");
const stmt::FuncDecl _findMSB("findMSB");
const stmt::FuncDecl _uaddCarry("uaddCarry");
const stmt::FuncDecl _umulExtended("umulExtended");
const stmt::FuncDecl _usubBorrow("usubBorrow");
// Image
const stmt::FuncDecl _imageAtomicAdd("imageAtomicAdd");
const stmt::FuncDecl _imageAtomicAnd("imageAtomicAnd");
const stmt::FuncDecl _imageAtomicCompSwap("imageAtomicCompSwap");
const stmt::FuncDecl _imageAtomicExchange("imageAtomicExchange");
const stmt::FuncDecl _imageAtomicMax("imageAtomicMax");
const stmt::FuncDecl _imageAtomicMin("imageAtomicMin");
const stmt::FuncDecl _imageAtomicOr("imageAtomicOr");
const stmt::FuncDecl _imageAtomicXor("imageAtomicXor");
const stmt::FuncDecl _imageLoad("imageLoad");
const stmt::FuncDecl _imageSamples("imageSamples");
const stmt::FuncDecl _imageSize("imageSize");
const stmt::FuncDecl _imageStore("imageStore");
// Atomic
const stmt::FuncDecl _atomicAdd("atomicAdd");
const stmt::FuncDecl _atomicAnd("atomicAnd");
const stmt::FuncDecl _atomicCompSwap("atomicCompSwap");
const stmt::FuncDecl _atomicCounter("atomicCounter");
const stmt::FuncDecl _atomicCounterDecrement("atomicCounterDecrement");
const stmt::FuncDecl _atomicCounterIncrement("atomicCounterIncrement");
const stmt::FuncDecl _atomicExchange("atomicExchange");
const stmt::FuncDecl _atomicMax("atomicMax");
const stmt::FuncDecl _atomicMin("atomicMin");
const stmt::FuncDecl _atomicOr("atomicOr");
const stmt::FuncDecl _atomicXor("atomicXor");
// Memory Barrier
const stmt::FuncDecl _barrier("barrier");
const stmt::FuncDecl _groupMemoryBarrier("groupMemoryBarrier");
const stmt::FuncDecl _memoryBarrier("memoryBarrier");
const stmt::FuncDecl _memoryBarrierAtomicCounter("memoryBarrierAtomicCounter");
const stmt::FuncDecl _memoryBarrierBuffer("memoryBarrierBuffer");
const stmt::FuncDecl _memoryBarrierImage("memoryBarrierImage");
const stmt::FuncDecl _memoryBarrierShared("memoryBarrierShared");


};
#endif